FROM ubuntu:xenial

RUN apt-get update && apt-get install -y apt-transport-https

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD && \
  echo "deb https://repo.iovisor.org/apt/xenial xenial main" | tee /etc/apt/sources.list.d/iovisor.list && \
  apt-get update && \
  apt-get install -y bcc-tools libbcc-examples

COPY client_linux_amd64 client